name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4 spotipy
          # Install Chrome browser and ChromeDriver (for Chrome browser)
          apt-get update
          apt-get install -y chromium-browser
          # Download and configure ChromeDriver
          CHROME_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d. -f1-3)
          wget -q "https://chromedriver.storage.googleapis.com/114.0.5735.16/chromedriver_linux64.zip" -O LATEST_RELEASE
          CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE)
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/

      - name: Run script
        run: python test.py
